matrix:
  include:
    - language: java
      jdk: openjdk10
      before_install:
        - cd api
      deploy:
        provider: heroku
        api_key:
          secure: $HEROKU_API_KEY
        app: $HEROKU_APP_NAME
    - language: node_js
      node_js:
        - lts/*
      before_install:
        - cd web
      script:
        - npm test
        - npm run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: web/build
        on:
          branch: master
