matrix:
  include:
    - language: java
      jdk:
        - oraclejdk8
      before_install:
        - cd api
      deploy:
        provider: heroku
        api_key:
          secure: $HEROKU_API_KEY
        app: gulliver-api
        skip_cleanup: true
        local_dir: target
    - language: node_js
      node_js:
        - 10
      before_install:
        - cd web
      script:
        - npm test
        - npm run build
